@host = localhost
@port = 8080
@baseUrl = http://{{host}}:{{port}}/api/v1


### ========================================
### 주문 생성 테스트
### ========================================

### 1. 주문 생성 기본 조회
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "storeId": 1,
  "pickupType": "STORE_PICKUP",
  "orderTotalPrice": 15000,
  "orderStatus": "PLACED",
  "orderItems": [
    {
      "itemId": 101,
      "itemType": "DRINK",
      "beverageSizeOption": "TALL",
      "beverageTemperatureOption": "HOT",
      "options": [{
        "id": 1,
        "syrupName": "WHIPPED_CREAM",
        "isRequired": false,
        "displayOrder": 1,
        "additonalPrice": 500,
        "quantity": 1
      }],
      "totalPrice": 8000,
      "itemPrice": 7500
    },
    {
      "itemId": 201,
      "itemType": "DESSERT",
      "beverageSizeOption": null,
      "beverageTemperatureOption": "ICE",
      "options": [],
      "totalPrice": 7000,
      "itemPrice": 7000
    }
  ]
}
