@host = localhost
@port = 8080
@baseUrl = http://{{host}}:{{port}}/api/v1
@accessToken = Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJJZCI6MiwiaWF0IjoxNzUxMjU2MjI3LCJleHAiOjE3NTEyNTgwMjd9.4bMiV04gNaOWxZPhiv35ffeMtZpwoUMbEa5cD-zXiDxoiawAo5abuOfnSzUnJARnP4o1StlziQpeBalhQb-gPw
### ========================================
### 카트 조회 테스트
### ========================================

### 1. 카트 조회 수정
GET {{baseUrl}}/carts?memberId=2
Authorization: {{accessToken}}

Content-Type: application/json
