@host = localhost
@port = 8080
@baseUrl = http://{{host}}:{{port}}/api/v1
@accessToken = 
### ========================================
### 카트 조회 테스트
### ========================================

### 1. 카트 조회 수정
GET {{baseUrl}}/carts?memberId=2
Authorization: {{accessToken}}

Content-Type: application/json
